name: R Array Traversal Benchmark

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual triggering
  schedule:
    # Run benchmark weekly on Sundays at 06:00 UTC
    - cron: '0 6 * * 0'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        r-version: ['4.3.0', 'release']  # Test on specific version and latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
        use-public-rspm: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev
          
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ~/R/Library
        key: ${{ runner.os }}-r${{ matrix.r-version }}-packages-${{ hashFiles('benchmark.R') }}
        restore-keys: ${{ runner.os }}-r${{ matrix.r-version }}-packages-
        
    - name: Install R dependencies
      run: |
        # Install required packages
        Rscript -e "install.packages(c('microbenchmark', 'ggplot2'), repos='https://cran.rstudio.com/', dependencies=TRUE)"
        
    - name: Display system information
      run: |
        echo "=== System Information ==="
        uname -a
        echo "=== CPU Information ==="
        lscpu
        echo "=== Memory Information ==="
        free -h
        echo "=== R Version ==="
        Rscript -e "cat('R version:', R.version.string, '\n')"
        echo "=== R Package Information ==="
        Rscript -e "cat('microbenchmark version:', packageVersion('microbenchmark'), '\n')"
        Rscript -e "cat('ggplot2 version:', packageVersion('ggplot2'), '\n')"
        
    - name: Run R Array Traversal Benchmark
      run: |
        echo "Starting R benchmark execution..."
        Rscript benchmark.R
        
    - name: Check benchmark results
      run: |
        echo "Benchmark completed successfully!"
        echo "Exit code: $?"
        
    - name: Upload benchmark artifacts (if any plots are generated)
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: benchmark-results-r${{ matrix.r-version }}
        path: |
          *.png
          *.pdf
          *.svg
        retention-days: 30
        
    - name: Display benchmark summary
      if: always()
      run: |
        echo "=== Benchmark Job Summary ==="
        echo "R Version: ${{ matrix.r-version }}"
        echo "OS: ubuntu-latest"
        echo "Timestamp: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
